

const MESSAGE_RECIEVED = "MESSAGE_RECIEVED";
const MESSAGE_SENT = "MESSAGE_SENT";
const MESSAGE_READ = "MESSAGE_READ";


const SETTINGS = "settings";
const PROFILE = "profile";
const LOGOUT = "logout";

export { MESSAGE_RECIEVED, MESSAGE_SENT, MESSAGE_READ, SETTINGS, PROFILE, LOGOUT};